### ISSUE TITLE
Resample Spectroradiometer data to the spectral bands of Sentinel-2

### ISSUE THREAD

**Issue by safalabolo** [serbinsh/R-FieldSpectra#13]
Dear Shawn,
congratulations for your job!
I would like to use the package in this way: I have spectroradiometer ASD reflectance data which I would like to resample to the spectral bands of Sentinel-2 using published spectral response functions.
With which command this is possible within the package.
Thank you so much for your answer.

**Comment by serbinsh** [comment]
@safalabolo I had a resample function in this package but have since let it lapse.  In the long run I am going to utilize the function in the PEcAnRTM package as this is already well-written and can support convolution for a number of sensors.  its easy for us to add Sentinel-2 as well

https://github.com/PecanProject/pecan/tree/develop/modules/rtm

**Comment by safalabolo** [comment]
Hi serbinsh,
thank you for sharing these updates.
All the best.
