### ISSUE TITLE
Workflow requirements for use

### ISSUE THREAD

**Issue by cmontes3** [serbinsh/R-FieldSpectra#18]
A couple of additional notes. This may be outside the original aims of the package, but when trying to process data somewhat differently than shown in example script the downstream functions fail. 

jump.correction() requires both jump locations specified. Assigning jump2 to NULL has no effect.
-> problem occurs when wanting to compare spectra across platforms that may not have the same data dimensions
-> -> ex. different hyperspectral camera only covers 350 - 800nm
-> problem occurs when wanting to subset out noisy data from canopy level measurements that fall at jump locations
-> -> function fails if reflectance value = 0 or NA

average.spec() requires jump.correction() output in order to function. Calls "spectra.diagnostics.csv" from jc_files directory
-> function fails if no spectra.diagnoistics.csv file present (i.e. trying to skip the jump.correction())

**Comment by serbinsh** [comment]
@cmontes3 yeah what you describe here, for the most part, are beyond the scope of the current package because this was originally designed very specifically for processing specific instruments. 

This sounds more like the need for a more general processing code base. I think this could be adapted to be more general it would just take some work.  Also you may also want to explore the spectrolab package https://github.com/meireles/spectrolab

Happy to talk more specifically about what you want to try and do and if we could could make some small changes here to accommodate.

**Comment by cmontes3** [comment]
Thanks @serbinsh . I'll take a look at the spectrolab. I was able to come up with a few work-arounds using FieldSpectra.
